# Generated by Django 6.0.4 on 2026-05-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0002_alter_clothingitem_category'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='clothingitem',
            name='wardrobe_cl_user_id_acb10a_idx',
        ),
        migrations.RemoveIndex(
            model_name='clothingitem',
            name='wardrobe_cl_user_id_f5f085_idx',
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='accessories',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='aesthetic',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='fit_silhouette',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='garment_type',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='is_complete_outfit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='occasion',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='season',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='styling_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='tags',
            field=models.TextField(blank=True, default=''),
        ),
    ]
