# Generated by Django 6.0.4 on 2026-06-05 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0004_wishlistitem'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='wishlistitem',
            new_name='wardrobe_wi_user_id_49cc2c_idx',
            old_name='wardrobe_wi_user_id_7f6d_idx',
        ),
        migrations.RenameIndex(
            model_name='wishlistitem',
            new_name='wardrobe_wi_user_id_f05d81_idx',
            old_name='wardrobe_wi_user_id_9ad4_idx',
        ),
    ]
